export interface NormalizedLead {
  id: string;
  market_region?: string | null;
  contact1_name?: string | null;
  contact1_email?: string | null;
  contact2_name?: string | null;
  contact2_email?: string | null;
  mls_curr_list_agent_name?: string | null;
  mls_curr_list_agent_email?: string | null;
  property_address?: string | null;
  property_city?: string | null;
  property_state?: string | null;
  property_postal_code?: string | null;
  property_type?: string | null;
  beds?: string | null;
  baths?: string | null;
  year_built?: string | null;
  square_footage?: string | null;
  lot_size_sqft?: string | null;
  wholesale_value?: number | null;
  assessed_total?: number | null;
  avm_value?: number | null;
  price_per_sq_ft?: number | null;
  mls_curr_status?: string | null;
  mls_curr_days_on_market?: string | null;
  converted: boolean;
  status?: string | null;
  source?: string | null;
  notes?: string | null;
  created_at: string | null;
  updated_at: string | null;
  company_name?: string | null;
  company_industry?: string | null;
  company_website?: string | null;
  company_notes?: string | null;
  county?: string | null;
  country?: string | null;
  lead_score?: number | null;
  assigned_to?: string | null;
  last_contacted_date?: string | null;
  next_follow_up_date?: string | null;
  conversion_date?: string | null;
  lost_reason?: string | null;
  tags?: string[] | null;
  custom_fields?: Record<string, any> | null;
  property_sf?: number | null;
  _primaryContact?: {
    name: string | null;
    email: string;
    type: string;
    contactType: 'owner' | 'agent';
  } | null;
}
